VALID_LOCATIONS = {
    "Craigslist": {
        "Africa": {
            "Egypt": {
                "Cairo": "https://cairo.craigslist.org/",
            },
            "Ethiopia": {
                "Addisababa": "https://addisababa.craigslist.org/",
            },
            "Ghana": {
                "Accra": "https://accra.craigslist.org/",
            },
            "Kenya": "https://kenya.craigslist.org/",
            "Morocco": {
                "Casablanca": "https://casablanca.craigslist.org/",
            },
            "South Africa": {
                "Cape Town": "https://capetown.craigslist.org/",
                "Durban": "https://durban.craigslist.org/",
                "Johannesburg": "https://johannesburg.craigslist.org/",
                "Pretoria": "https://pretoria.craigslist.org/",
            },
            "Tunisia": {
                "Tunis": "https://tunis.craigslist.org/",
            },
        },
        "Asia": {
            "Bangladesh": "https://bangladesh.craigslist.org/",
            "China": {
                "Beijing": "https://beijing.craigslist.org/",
                "Chengdu": "https://chengdu.craigslist.org/",
                "Chongqing": "https://chongqing.craigslist.org/",
                "Dalian": "https://dalian.craigslist.org/",
                "Guangzhou": "https://guangzhou.craigslist.org/",
                "Gangzhou": "https://hangzhou.craigslist.org/",
                "Nanjing": "https://nanjing.craigslist.org/",
                "Shanghai": "https://shanghai.craigslist.org/",
                "Shenyang": "https://shenyang.craigslist.org/",
                "Shenzhen": "https://shenzhen.craigslist.org/",
                "Wuhan": "https://wuhan.craigslist.org/",
                "Xian": "https://xian.craigslist.org/",
            },
            "Hong Kong": "https://hongkong.craigslist.org/",
            "India": {
                "Ahmedabad": "https://ahmedabad.craigslist.org/",
                "Bangalore": "https://bangalore.craigslist.org/",
                "Bhubaneswar": "https://bhubaneswar.craigslist.org/",
                "Chandigarh": "https://chandigarh.craigslist.org/",
                "Chennai": "https://chennai.craigslist.org/",
                "Delhi": "https://delhi.craigslist.org/",
                "Goa": "https://goa.craigslist.org/",
                "Hyderabad": "https://hyderabad.craigslist.org/",
                "Indore": "https://indore.craigslist.org/",
                "Jaipur": "https://jaipur.craigslist.org/",
                "Kerala": "https://kerala.craigslist.org/",
                "Kolkata": "https://kolkata.craigslist.org/",
                "Lucknow": "https://lucknow.craigslist.org/",
                "Mumbai": "https://mumbai.craigslist.org/",
                "Pune": "https://pune.craigslist.org/",
                "Surat": "https://surat.craigslist.org/",
                "Surat Surat": "https://surat.craigslist.org/",
            },
            "Indonesia": {
                "Jakarta": "https://jakarta.craigslist.org/",
            },
            "Iran": {
                "Tehran": "https://tehran.craigslist.org/",
            },
            "Iraq": {
                "Baghdad": "https://baghdad.craigslist.org/",
            },
            "Israel": {
                "Haifa": "https://haifa.craigslist.org/",
                "Jerusalem": "https://jerusalem.craigslist.org/",
                "Tel Aviv": "https://telaviv.craigslist.org/",
            },
            "Palestine": {
                "West Bank": "https://ramallah.craigslist.org/",
                "Ramallah": "https://ramallah.craigslist.org/",
            },
            "Japan": {
                "Fukuoka": "https://fukuoka.craigslist.org/",
                "Hiroshima": "https://hiroshima.craigslist.org/",
                "Nagoya": "https://nagoya.craigslist.org/",
                "Okinawa": "https://okinawa.craigslist.org/",
                "Osaka": "https://osaka.craigslist.org/",
                "Kobe": "https://osaka.craigslist.org/",
                "Kyoto": "https://osaka.craigslist.org/",
                "Sapporo": "https://sapporo.craigslist.org/",
                "Sendai": "https://sendai.craigslist.org/",
                "Tokyo": "https://tokyo.craigslist.org/",
            },
            "Korea": {
                "Seoul": "https://seoul.craigslist.org/",
            },
            "Kuwait": "https://kuwait.craigslist.org/",
            "Lebanon": {
                "Beirut": "https://beirut.craigslist.org/",
            },
            "Malaysia": "https://malaysia.craigslist.org/",
            "Pakistan": "https://pakistan.craigslist.org/",
            "Philippines": {
                "Bacolod": "https://bacolod.craigslist.org/",
                "Bicol region": "https://naga.craigslist.org/",
                "Bicol": "https://naga.craigslist.org/",
                "Naga": "https://naga.craigslist.org/",
                "CDO": "https://cdo.craigslist.org/",
                "Cagayan De Oro": "https://cdo.craigslist.org/",
                "Cebu": "https://cebu.craigslist.org/",
                "Davao": "https://davaocity.craigslist.org/",
                "Davao City": "https://davaocity.craigslist.org/",
                "Iloilo": "https://iloilo.craigslist.org/",
                "Manila": "https://manila.craigslist.org/",
                "Pampanga": "https://pampanga.craigslist.org/",
                "Zamboanga": "https://zamboanga.craigslist.org/",
            },
            "Singapore": "https://singapore.craigslist.org/",
            "Taiwan": {
                "Taipei": "https://taipei.craigslist.org/",
            },
            "Thailand": {
                "Bangkok": "https://bangkok.craigslist.org/",
            },
            "UAE": {
                "Dubai": "https://dubai.craigslist.org/",
            },
            "Vietnam": "https://vietnam.craigslist.org/",
        },
        "Europe": {
            "Austria": {
                "Vienna": "https://vienna.craigslist.org/",
            },
            "Belgium": {"Brussels": "https://brussels.craigslist.org/,"},
            "Bulgaria": "https://bulgaria.craigslist.org/",
            "Croatia": {
                "Zagreb": "https://zagreb.craigslist.org/",
            },
            "Czech": {
                "Prague": "https://prague.craigslist.org/",
            },
            "Denmark": {
                "Copenhagen": "https://copenhagen.craigslist.org/",
            },
            "Finland": {
                "Helsinki": "https://helsinki.craigslist.org/",
            },
            "France": {
                "Bordeaux": "https://bordeaux.craigslist.org/",
                "Brittany": "https://rennes.craigslist.org/",
                "Rennes": "https://rennes.craigslist.org/",
                "Grenoble": "https://grenoble.craigslist.org/",
                "Lille": "https://lille.craigslist.org/",
                "Loire Valley": "https://loire.craigslist.org/",
                "Loire": "https://loire.craigslist.org/",
                "Lyon": "https://lyon.craigslist.org/",
                "Marseilles": "https://marseilles.craigslist.org/",
                "Montpellier": "https://montpellier.craigslist.org/",
                "Nice": "https://cotedazur.craigslist.org/",
                "Cote Dazur": "https://cotedazur.craigslist.org/",
                "Normandy": "https://rouen.craigslist.org/",
                "Rouen": "https://rouen.craigslist.org/",
                "Paris": "https://paris.craigslist.org/",
                "Strasbourg": "https://strasbourg.craigslist.org/",
                "Toulouse": "https://toulouse.craigslist.org/",
            },
            "Germany": {
                "Berlin": "https://berlin.craigslist.org/",
                "Bremen": "https://bremen.craigslist.org/",
                "Cologne": "https://cologne.craigslist.org/",
                "Dresden": "https://dresden.craigslist.org/",
                "Dusseldorf": "https://dusseldorf.craigslist.org/",
                "Essen": "https://essen.craigslist.org/",
                "Ruhr": "https://essen.craigslist.org/",
                "Frankfurt": "https://frankfurt.craigslist.org/",
                "Hamburg": "https://hamburg.craigslist.org/",
                "Hannover": "https://hannover.craigslist.org/",
                "Heidelberg": "https://heidelberg.craigslist.org/",
                "Kaiserslautern": "https://kaiserslautern.craigslist.org/",
                "Leipzig": "https://leipzig.craigslist.org/",
                "Munich": "https://munich.craigslist.org/",
                "Nuremberg": "https://nuremberg.craigslist.org/",
                "Stuttgart": "https://stuttgart.craigslist.org/",
            },
            "Greece": {
                "Athens": "https://athens.craigslist.org/",
            },
            "Hungary": {
                "Budapest": "https://budapest.craigslist.org/",
            },
            "Iceland": {
                "Reykjavik": "https://reykjavik.craigslist.org/",
            },
            "Ireland": {
                "Dublin": "https://dublin.craigslist.org/",
            },
            "Italy": {
                "Bologna": "https://bologna.craigslist.org/",
                "Florence": "https://florence.craigslist.org/",
                "Tuscany": "https://florence.craigslist.org/",
                "Genoa": "https://genoa.craigslist.org/",
                "Milan": "https://milan.craigslist.org/",
                "Naples": "https://naples.craigslist.org/",
                "Napoli": "https://naples.craigslist.org/",
                "Campania": "https://naples.craigslist.org/",
                "Perugia": "https://perugia.craigslist.org/",
                "Rome": "https://rome.craigslist.org/",
                "Sardinia": "https://sardinia.craigslist.org/",
                "Sicily": "https://sicily.craigslist.org/",
                "Sicilia": "https://sicily.craigslist.org/",
                "Torino": "https://torino.craigslist.org/",
                "Venice": "https://venice.craigslist.org/",
                "Veneto": "https://venice.craigslist.org/",
            },
            "Luxembourg": "https://luxembourg.craigslist.org/",
            "Netherlands": {
                "Amsterdam": "https://amsterdam.craigslist.org/",
                "Randstad": "https://amsterdam.craigslist.org/",
            },
            "Norway": {
                "Oslo": "https://oslo.craigslist.org/",
            },
            "Poland": {
                "Warsaw": "https://warsaw.craigslist.org/",
            },
            "Portugal": {
                "Faro": "https://faro.craigslist.org/",
                "Algarve": "https://faro.craigslist.org/",
                "Lisbon": "https://lisbon.craigslist.org/",
                "Porto": "https://porto.craigslist.org/",
            },
            "Romania": {
                "Bucharest": "https://bucharest.craigslist.org/",
            },
            "Russia": {
                "Moscow": "https://moscow.craigslist.org/",
                "St Petersburg": "https://stpetersburg.craigslist.org/",
            },
            "Spain": {
                "Alicante": "https://alicante.craigslist.org/",
                "Baleares": "https://baleares.craigslist.org/",
                "Barcelona": "https://barcelona.craigslist.org/",
                "Bilbao": "https://bilbao.craigslist.org/",
                "Cadiz": "https://cadiz.craigslist.org/",
                "Canarias": "https://canarias.craigslist.org/",
                "Granada": "https://granada.craigslist.org/",
                "Madrid": "https://madrid.craigslist.org/",
                "Malaga": "https://malaga.craigslist.org/",
                "Sevilla": "https://sevilla.craigslist.org/",
                "Valencia": "https://valencia.craigslist.org/",
            },
            "Sweden": {
                "Stockholm": "https://stockholm.craigslist.org/",
            },
            "Switzerland": {
                "Basel": "https://basel.craigslist.org/",
                "Bern": "https://bern.craigslist.org/",
                "Geneva": "https://geneva.craigslist.org/",
                "Lausanne": "https://lausanne.craigslist.org/",
                "Zurich": "https://zurich.craigslist.org/",
            },
            "Turkey": {
                "Istanbul": "https://istanbul.craigslist.org/",
            },
            "Ukraine": "https://ukraine.craigslist.org/",
            "United Kingdom": {
                "Aberdeen": "https://aberdeen.craigslist.org/",
                "Bath": "https://bath.craigslist.org/",
                "Belfast": "https://belfast.craigslist.org/",
                "Birmingham": "https://birmingham.craigslist.org/",
                "West Mids": "https://birmingham.craigslist.org/",
                "Brighton": "https://brighton.craigslist.org/",
                "Bristol": "https://bristol.craigslist.org/",
                "Cambridge": "https://cambridge.craigslist.org/",
                "Cardiff": "https://cardiff.craigslist.org/",
                "Wales": "https://cardiff.craigslist.org/",
                "Coventry": "https://coventry.craigslist.org/",
                "Derby": "https://derby.craigslist.org/",
                "Devon": "https://devon.craigslist.org/",
                "Cornwall": "https://devon.craigslist.org/",
                "Dundee": "https://dundee.craigslist.org/",
                "Norwich": "https://norwich.craigslist.org/",
                "East Anglia": "https://norwich.craigslist.org/",
                "East Mids": "https://eastmids.craigslist.org/",
                "Edinburgh": "https://edinburgh.craigslist.org/",
                "Essex": "https://essex.craigslist.org/",
                "Glasgow": "https://glasgow.craigslist.org/",
                "Hampshire": "https://hampshire.craigslist.org/",
                "Kent": "https://kent.craigslist.org/",
                "Leeds": "https://leeds.craigslist.org/",
                "Liverpool": "https://liverpool.craigslist.org/",
                "London": "https://london.craigslist.org/",
                "Manchester": "https://manchester.craigslist.org/",
                "New Castle": "https://newcastle.craigslist.org/",
                "NE England": "https://newcastle.craigslist.org/",
                "Nottingham": "https://nottingham.craigslist.org/",
                "Oxford": "https://oxford.craigslist.org/",
                "Sheffield": "https://sheffield.craigslist.org/",
            },
        },
        "Latin America": {
            "Argentina": {
                "Buenos Aires": "https://buenosaires.craigslist.org/",
            },
            "Bolivia": {
                "Lapaz": "https://lapaz.craigslist.org/",
            },
            "Brazil": {
                "Belo Horizonte": "https://belohorizonte.craigslist.org/",
                "Brasilia": "https://brasilia.craigslist.org/",
                "Curitiba": "https://curitiba.craigslist.org/",
                "Fortaleza": "https://fortaleza.craigslist.org/",
                "Porto Alegre": "https://portoalegre.craigslist.org/",
                "Recife": "https://recife.craigslist.org/",
                "Rio": "https://rio.craigslist.org/",
                "Rio De Janeiro": "https://rio.craigslist.org/",
                "Salvador": "https://salvador.craigslist.org/",
                "Bahia": "https://salvador.craigslist.org/",
                "Sao Paulo": "https://saopaulo.craigslist.org/",
            },
            "Caribbean": "https://caribbean.craigslist.org/",
            "Chile": {
                "Santiago": "https://santiago.craigslist.org/",
            },
            "Colombia": "https://colombia.craigslist.org/",
            "Costa Rica": "https://costarica.craigslist.org/",
            "Dominican": {
                "Santo Domingo": "https://santodomingo.craigslist.org/",
            },
            "Ecuador": {
                "Quito": "https://quito.craigslist.org/",
            },
            "El Salvador": "https://elsalvador.craigslist.org/",
            "Guatemala": "https://guatemala.craigslist.org/",
            "Mexico": {
                "Acapulco": "https://acapulco.craigslist.org/",
                "Baja": "https://bajasur.craigslist.org/",
                "Chihuahua": "https://chihuahua.craigslist.org/",
                "Juarez": "https://juarez.craigslist.org/",
                "Ciudad Juarez": "https://juarez.craigslist.org/",
                "Guadalajara": "https://guadalajara.craigslist.org/",
                "Guanajuato": "https://guanajuato.craigslist.org/",
                "Hermosillo": "https://hermosillo.craigslist.org/",
                "Mazatlan": "https://mazatlan.craigslist.org/",
                "Mexico City": "https://mexicocity.craigslist.org/",
                "Monterrey": "https://monterrey.craigslist.org/",
                "Oaxaca": "https://oaxaca.craigslist.org/",
                "Puebla": "https://puebla.craigslist.org/",
                "Puerto Vallarta": "https://pv.craigslist.org/",
                "Tijuana": "https://tijuana.craigslist.org/",
                "Veracruz": "https://veracruz.craigslist.org/",
                "Yucatan": "https://yucatan.craigslist.org/",
            },
            "Nicaragua": {
                "Managua": "https://managua.craigslist.org/",
            },
            "Panama": "https://panama.craigslist.org/",
            "Peru": {
                "Lima": "https://lima.craigslist.org/",
            },
            "Uruguay": {
                "Montevideo": "https://montevideo.craigslist.org/",
            },
            "Venezuela": {
                "Caracas": "https://caracas.craigslist.org/",
            },
        },
        "North America": {
            "Canada": {
                "Alberta": {
                    "Calgary": "https://calgary.craigslist.org/",
                    "Edmonton": "https://edmonton.craigslist.org/",
                    "Ft McMurray": "https://ftmcmurray.craigslist.org/",
                    "Lethbridge": "https://lethbridge.craigslist.org/",
                    "Medicine Hat": "https://hat.craigslist.org/",
                    "Peace River County": "https://peace.craigslist.org/",
                    "Peace River": "https://peace.craigslist.org/",
                    "Red Deer": "https://reddeer.craigslist.org/",
                },
                "British Columbia": {
                    "Cariboo": "https://cariboo.craigslist.org/",
                    "Comox Valley": "https://comoxvalley.craigslist.org/",
                    "Abbotsford": "https://abbotsford.craigslist.org/",
                    "Fraser Valley": "https://abbotsford.craigslist.org/",
                    "Kamloops": "https://kamloops.craigslist.org/",
                    "Kelowna": "https://kelowna.craigslist.org/",
                    "Okanagan": "https://kelowna.craigslist.org/",
                    "Kootenays": "https://kootenays.craigslist.org/",
                    "Nanaimo": "https://nanaimo.craigslist.org/",
                    "Prince George": "https://princegeorge.craigslist.org/",
                    "Skeena River": "https://skeena.craigslist.org/",
                    "Bulkley Valley": "https://skeena.craigslist.org/",
                    "Sunshine Coast": "https://sunshine.craigslist.org/",
                    "Vancouver": "https://vancouver.craigslist.org/",
                    "Victoria": "https://victoria.craigslist.org/",
                    "Whistler": "https://whistler.craigslist.org/",
                },
                "Manitoba": {
                    "Winnipeg": "https://winnipeg.craigslist.org/",
                },
                "New Brunswick": "https://newbrunswick.craigslist.org/",
                "Newfoundland": {
                    "St Johns": "https://newfoundland.craigslist.org/",
                },
                "Northwest Territories": {
                    "Territories": "https://territories.craigslist.org/",
                    "Yellow Knife": "https://yellowknife.craigslist.org/",
                },
                "Nova Scotia": {
                    "Halifax": "https://halifax.craigslist.org/",
                },
                "Ontario": {
                    "Barrie": "https://barrie.craigslist.org/",
                    "Belle Ville": "https://belleville.craigslist.org/",
                    "Brantford": "https://brantford.craigslist.org/",
                    "Woodstock": "https://brantford.craigslist.org/",
                    "Chatham": "https://chatham.craigslist.org/",
                    "Kent": "https://chatham.craigslist.org/",
                    "Cornwall": "https://cornwall.craigslist.org/",
                    "Guelph": "https://guelph.craigslist.org/",
                    "Hamilton": "https://hamilton.craigslist.org/",
                    "Burlington": "https://hamilton.craigslist.org/",
                    "Kingston": "https://kingston.craigslist.org/",
                    "Kitchener": "https://kitchener.craigslist.org/",
                    "Waterloo": "https://kitchener.craigslist.org/",
                    "Cambridge": "https://kitchener.craigslist.org/",
                    "London ON": "https://londonon.craigslist.org/",
                    "Niagara": "https://niagara.craigslist.org/",
                    "Ottawa": "https://ottawa.craigslist.org/",
                    "Hull": "https://ottawa.craigslist.org/",
                    "Gatineau": "https://ottawa.craigslist.org/",
                    "Owen Sound": "https://owensound.craigslist.org/",
                    "Peterborough": "https://peterborough.craigslist.org/",
                    "Sarnia": "https://sarnia.craigslist.org/",
                    "Sault Ste Marie": "https://soo.craigslist.org/",
                    "Sudbury": "https://sudbury.craigslist.org/",
                    "Thunder Bay": "https://thunderbay.craigslist.org/",
                    "Toronto": "https://toronto.craigslist.org/",
                    "Windsor": "https://windsor.craigslist.org/",
                },
                "Prince Edward": {
                    "Prince Edward Island": "https://pei.craigslist.org/",
                },
                "Quebec": {
                    "Montreal": "https://montreal.craigslist.org/",
                    "Quebec": "https://quebec.craigslist.org/",
                    "Saguenay": "https://saguenay.craigslist.org/",
                    "Sherbrooke": "https://sherbrooke.craigslist.org/",
                    "trois Rivieres": "https://troisrivieres.craigslist.org/",
                },
                "Saskatchewan": {
                    "Regina": "https://regina.craigslist.org/",
                    "Saskatoon": "https://saskatoon.craigslist.org/",
                },
                "Yukon": {
                    "Whitehorse": "https://whitehorse.craigslist.org/",
                },
            },
            "United States": {
                "Lower 48": {
                    "Alabama": {
                        "Auburn": "https://auburn.craigslist.org/",
                        "Birmingham": "https://bham.craigslist.org/",
                        "Dothan": "https://dothan.craigslist.org/",
                        "Florence": "https://shoals.craigslist.org/",
                        "Muscle Shoals": "https://shoals.craigslist.org/",
                        "Gadsden": "https://shoals.craigslist.org/",
                        "Anniston": "https://shoals.craigslist.org/",
                        "Huntsville": "https://huntsville.craigslist.org/",
                        "Decatur": "https://huntsville.craigslist.org/",
                        "Mobile": "https://mobile.craigslist.org/",
                        "Montgomery": "https://montgomery.craigslist.org/",
                        "Tuscaloosa": "https://tuscaloosa.craigslist.org/",
                    },
                    "Arizona": {
                        "Flagstaff": "https://flagstaff.craigslist.org/",
                        "Sedona": "https://flagstaff.craigslist.org/",
                        "Mohave County": "https://mohave.craigslist.org/",
                        "Mohave": "https://mohave.craigslist.org/",
                        "Phoenix": "https://phoenix.craigslist.org/",
                        "Prescott": "https://prescott.craigslist.org/",
                        "Show Low": "https://showlow.craigslist.org/",
                        "Sierra Vista": "https://sierravista.craigslist.org/",
                        "Tucson": "https://tucson.craigslist.org/",
                        "Yuma": "https://yuma.craigslist.org/",
                    },
                    "Arkansas": {
                        "Fayetteville": "https://fayar.craigslist.org/",
                        "Fort Smith": "https://fortsmith.craigslist.org/",
                        "Jonesboro": "https://jonesboro.craigslist.org/",
                        "Little Rock": "https://littlerock.craigslist.org/",
                        "Texarkana": "https://texarkana.craigslist.org/",
                    },
                    "California": {
                        "Bakersfield": "https://bakersfield.craigslist.org/",
                        "Chico": "https://chico.craigslist.org/",
                        "Fresno": "https://fresno.craigslist.org/",
                        "Madera": "https://fresno.craigslist.org/",
                        "Gold Country": "https://goldcountry.craigslist.org/",
                        "Hanford": "https://hanford.craigslist.org/",
                        "Corcoran": "https://hanford.craigslist.org/",
                        "Humboldt County": "https://humboldt.craigslist.org/",
                        "Humboldt": "https://humboldt.craigslist.org/",
                        "Imperial County": "https://imperial.craigslist.org/",
                        "Imperial": "https://imperial.craigslist.org/",
                        "Inland Empire": "https://inlandempire.craigslist.org/",
                        "Los Angeles": "https://losangeles.craigslist.org/",
                        "LA": "https://losangeles.craigslist.org/",
                        "Mendocino County": "https://mendocino.craigslist.org/",
                        "Merced": "https://merced.craigslist.org/",
                        "Modesto": "https://modesto.craigslist.org/",
                        "Monterey Bay": "https://monterey.craigslist.org/",
                        "Orange County": "https://orangecounty.craigslist.org/",
                        "Palm Springs": "https://palmsprings.craigslist.org/",
                        "Redding": "https://redding.craigslist.org/",
                        "Sacramento": "https://sacramento.craigslist.org/",
                        "San Diego": "https://sandiego.craigslist.org/",
                        "San Francisco": "https://sfbay.craigslist.org/",
                        "SF": "https://sfbay.craigslist.org/",
                        "Bay Area": "https://sfbay.craigslist.org/",
                        "San Luis Obispo": "https://slo.craigslist.org/",
                        "Santa Barbara": "https://santabarbara.craigslist.org/",
                        "Santa Maria": "https://santamaria.craigslist.org/",
                        "Siskiyou County": "https://siskiyou.craigslist.org/",
                        "Siskiyou": "https://siskiyou.craigslist.org/",
                        "Stockton": "https://stockton.craigslist.org/",
                        "Susanville": "https://susanville.craigslist.org/",
                        "Ventura County": "https://ventura.craigslist.org/",
                        "Ventura": "https://ventura.craigslist.org/",
                        "Visalia": "https://visalia.craigslist.org/",
                        "Tulare": "https://visalia.craigslist.org/",
                        "Yuba": "https://yubasutter.craigslist.org/",
                        "Sutter": "https://yubasutter.craigslist.org/",
                    },
                    "Colorado": {
                        "Boulder": "https://boulder.craigslist.org/",
                        "Colorado Springs": "https://cosprings.craigslist.org/",
                        "Denver": "https://denver.craigslist.org/",
                        "East Colorado": "https://eastco.craigslist.org/",
                        "East CO": "https://eastco.craigslist.org/",
                        "Fort Collins": "https://fortcollins.craigslist.org/",
                        "North Colorado": "https://fortcollins.craigslist.org/",
                        "North CO": "https://fortcollins.craigslist.org/",
                        "High Rockies": "https://rockies.craigslist.org/",
                        "Rockies": "https://rockies.craigslist.org/",
                        "Pueblo": "https://pueblo.craigslist.org/",
                        "Western Slope": "https://westslope.craigslist.org/",
                        "West Slope": "https://westslope.craigslist.org/",
                        "West CO": "https://westslope.craigslist.org/",
                    },
                    "Connecticut": {
                        "East Connecticut": "https://newlondon.craigslist.org/",
                        "East CT": "https://newlondon.craigslist.org/",
                        "New London": "https://newlondon.craigslist.org/",
                        "Hartford": "https://hartford.craigslist.org/",
                        "New Haven": "https://newhaven.craigslist.org/",
                        "Northwest Connecticut": "https://newhaven.craigslist.org/",
                        "Northwest CT": "https://newhaven.craigslist.org/",
                    },
                    "Delaware": "https://delaware.craigslist.org/",
                    "District of Columbia": "https://washingtondc.craigslist.org/",
                    "Washington DC": "https://washingtondc.craigslist.org/",
                    "DC": "https://washingtondc.craigslist.org/",
                    "Florida": {
                        "Broward County": "https://miami.craigslist.org/brw/",
                        "Daytona Beach": "https://daytona.craigslist.org/",
                        "Florida Keys": "https://keys.craigslist.org/",
                        "Key West": "https://keys.craigslist.org/",
                        "Fort Lauderdale": "https://fortlauderdale.craigslist.org/",
                        "Fort Myers": "https://fortmyers.craigslist.org/",
                        "Southwest Florida": "https://fortmyers.craigslist.org/",
                        "Southwest FL": "https://fortmyers.craigslist.org/",
                        "Gainesville": "https://gainesville.craigslist.org/",
                        "Heartland Florida": "https://cfl.craigslist.org/",
                        "Florida Heartland": "https://cfl.craigslist.org/",
                        "Jacksonville": "https://jacksonville.craigslist.org/",
                        "Lakeland": "https://lakeland.craigslist.org/",
                        "Miami": "https://miami.craigslist.org/",
                        "Miami Dade": "https://miami.craigslist.org/",
                        "Miami Dade County": "https://miami.craigslist.org/",
                        "Dade County": "https://miami.craigslist.org/",
                        "North Central Florida": "https://lakecity.craigslist.org/",
                        "North Central FL": "https://lakecity.craigslist.org/",
                        "Lake City": "https://lakecity.craigslist.org/",
                        "Ocala": "https://ocala.craigslist.org/",
                        "Okaloosa": "https://okaloosa.craigslist.org/",
                        "Walton": "https://okaloosa.craigslist.org/",
                        "Orlando": "https://orlando.craigslist.org/",
                        "Panama City": "https://panamacity.craigslist.org/",
                        "Pensacola": "https://pensacola.craigslist.org/",
                        "Sarasota": "https://sarasota.craigslist.org/",
                        "Bradenton": "https://sarasota.craigslist.org/",
                        "South Florida": "https://miami.craigslist.org/",
                        "South FL": "https://miami.craigslist.org/",
                        "Space Coast": "https://spacecoast.craigslist.org/",
                        "St Augustine": "https://staugustine.craigslist.org/",
                        "Tallahassee": "https://tallahassee.craigslist.org/",
                        "Tampa": "https://tampa.craigslist.org/",
                        "Tampa Bay": "https://tampa.craigslist.org/",
                        "Tampa Bay Area": "https://tampa.craigslist.org/",
                        "Treasure Coast": "https://treasure.craigslist.org/",
                        "Palm Beach": "https://miami.craigslist.org/",
                        "Palm Beach County": "https://miami.craigslist.org/",
                    },
                    "Georgia": {
                        "Albany GA": "https://albanyga.craigslist.org/",
                        "Athens GA": "https://athensga.craigslist.org/",
                        "Atlanta": "https://atlanta.craigslist.org/",
                        "ATL": "https://atlanta.craigslist.org/",
                        "Augusta": "https://augusta.craigslist.org/",
                        "Brunswick": "https://brunswick.craigslist.org/",
                        "Columbus GA": "https://columbusga.craigslist.org/",
                        "Macon": "https://macon.craigslist.org/",
                        "Warner Robins": "https://macon.craigslist.org/",
                        "Northwest Georgia": "https://macon.craigslist.org/",
                        "Northwest GA": "https://macon.craigslist.org/",
                        "Savannah": "https://savannah.craigslist.org/",
                        "Hinesville": "https://savannah.craigslist.org/",
                        "Statesboro": "https://statesboro.craigslist.org/",
                        "Valdosta": "https://valdosta.craigslist.org/",
                    },
                    "Idaho": {
                        "Boise": "https://boise.craigslist.org/",
                        "East Idaho": "https://boise.craigslist.org/",
                        "Lewiston": "https://lewiston.craigslist.org/",
                        "Clarkston": "https://lewiston.craigslist.org/",
                        "Twin Falls": "https://twinfalls.craigslist.org/",
                    },
                    "Illinois": {
                        "Bloomington IL": "https://bn.craigslist.org/",
                        "Normal": "https://bn.craigslist.org/",
                        "Chambana": "https://chambana.craigslist.org/",
                        "Urbana": "https://chambana.craigslist.org/",
                        "Chambana Urbana": "https://chambana.craigslist.org/",
                        "Chicago": "https://chicago.craigslist.org/",
                        "Decatur": "https://decatur.craigslist.org/",
                        "La Salle": "https://lasalle.craigslist.org/",
                        "La Salle County": "https://lasalle.craigslist.org/",
                        "Mattoon": "https://mattoon.craigslist.org/",
                        "Charleston": "https://mattoon.craigslist.org/",
                        "Peoria": "https://peoria.craigslist.org/",
                        "Rockford": "https://rockford.craigslist.org/",
                        "South Illinois": "https://carbondale.craigslist.org/",
                        "South IL": "https://carbondale.craigslist.org/",
                        "Carbondale": "https://carbondale.craigslist.org/",
                        "Springfield": "https://springfieldil.craigslist.org/",
                        "West Illinois": "https://quincy.craigslist.org/",
                        "West IL": "https://quincy.craigslist.org/",
                        "Quincy": "https://quincy.craigslist.org/",
                    },
                    "Indiana": {
                        "Bloomington IN": "https://bloomington.craigslist.org/",
                        "Evansville": "https://evansville.craigslist.org/",
                        "Fort Wayne": "https://fortwayne.craigslist.org/",
                        "Indianapolis": "https://indianapolis.craigslist.org/",
                        "Kokomo": "https://kokomo.craigslist.org/",
                        "Lafayette": "https://tippecanoe.craigslist.org/",
                        "Tippecanoe County": "https://tippecanoe.craigslist.org/",
                        "Muncie": "https://muncie.craigslist.org/",
                        "Anderson": "https://muncie.craigslist.org/",
                        "Richmond": "https://richmondin.craigslist.org/",
                        "South Bend": "https://southbend.craigslist.org/",
                        "Michiana": "https://southbend.craigslist.org/",
                        "Terre Haute": "https://terrehaute.craigslist.org/",
                    },
                    "Iowa": {
                        "Ames": "https://ames.craigslist.org/",
                        "Cedar Rapids": "https://cedarrapids.craigslist.org/",
                        "Des Moines": "https://desmoines.craigslist.org/",
                        "Dubuque": "https://dubuque.craigslist.org/",
                        "Fort Dodge": "https://fortdodge.craigslist.org/",
                        "Iowa City": "https://iowacity.craigslist.org/",
                        "Mason City": "https://masoncity.craigslist.org/",
                        "Quad Cities": "https://quadcities.craigslist.org/",
                        "Quad City": "https://quadcities.craigslist.org/",
                        "Sioux City": "https://siouxcity.craigslist.org/",
                        "Southeast Iowa": "https://ottumwa.craigslist.org/",
                        "Ottumwa": "https://ottumwa.craigslist.org/",
                        "Waterloo": "https://waterloo.craigslist.org/",
                        "Cedar Falls": "https://waterloo.craigslist.org/",
                    },
                    "Kansas": {
                        "Lawrence": "https://lawrence.craigslist.org/",
                        "Manhattan": "https://ksu.craigslist.org/",
                        "Northwest Kansas": "https://nwks.craigslist.org/",
                        "Northwest KS": "https://nwks.craigslist.org/",
                        "Salina": "https://salina.craigslist.org/",
                        "Southeast Kansas": "https://seks.craigslist.org/",
                        "Southeast KS": "https://seks.craigslist.org/",
                        "Southwest Kansas": "https://swks.craigslist.org/",
                        "Southwest KS": "https://swks.craigslist.org/",
                        "Topeka": "https://topeka.craigslist.org/",
                        "Wichita": "https://wichita.craigslist.org/",
                    },
                    "Kentucky": {
                        "Bowling Green": "https://bgky.craigslist.org/",
                        "East Kentucky": "https://eastky.craigslist.org/",
                        "East KY": "https://eastky.craigslist.org/",
                        "Lexington": "https://lexington.craigslist.org/",
                        "Louisville": "https://louisville.craigslist.org/",
                        "Owensboro": "https://owensboro.craigslist.org/",
                        "West Kentucky": "https://westky.craigslist.org/",
                        "West KY": "https://westky.craigslist.org/",
                    },
                    "Louisiana": {
                        "Baton Rouge": "https://batonrouge.craigslist.org/",
                        "Central Louisiana": "https://cenla.craigslist.org/",
                        "Central LA": "https://cenla.craigslist.org/",
                        "Houma": "https://houma.craigslist.org/",
                        "Lafayetta": "https://lafayette.craigslist.org/",
                        "Lake Charles": "https://lakecharles.craigslist.org/",
                        "Monroe": "https://monroe.craigslist.org/",
                        "New Orleans": "https://neworleans.craigslist.org/",
                        "Shreveport": "https://shreveport.craigslist.org/",
                    },
                    "Maine": "https://maine.craigslist.org/",
                    "Maryland": {
                        "Annapolis": "https://annapolis.craigslist.org/",
                        "Baltimore": "https://baltimore.craigslist.org/",
                        "Eastern Shore": "https://easternshore.craigslist.org/",
                        "Frederick": "https://frederick.craigslist.org/",
                        "South Maryland": "https://smd.craigslist.org/",
                        "South MD": "https://smd.craigslist.org/",
                        "West Maryland": "https://westmd.craigslist.org/",
                        "West MD": "https://westmd.craigslist.org/",
                    },
                    "Massachusetts": {
                        "Boston": "https://boston.craigslist.org/",
                        "Cape Cod": "https://capecod.craigslist.org/",
                        "South Coast": "https://southcoast.craigslist.org/",
                        "West Mass": "https://westernmass.craigslist.org/",
                        "West Massachusetts": "https://westernmass.craigslist.org/",
                        "West MA": "https://westernmass.craigslist.org/",
                        "Worcester": "https://worcester.craigslist.org/",
                        "Central Mass": "https://worcester.craigslist.org/",
                        "Central Massachusetts": "https://worcester.craigslist.org/",
                        "Central MA": "https://worcester.craigslist.org/",
                    },
                    "Michigan": {
                        "Ann Arbor": "https://annarbor.craigslist.org/",
                        "Battle Creek": "https://battlecreek.craigslist.org/",
                        "Central Michigan": "https://centralmich.craigslist.org/",
                        "Central MI": "https://centralmich.craigslist.org/",
                        "Detroit": "https://detroit.craigslist.org/",
                        "Flint": "https://flint.craigslist.org/",
                        "Grand Rapids": "https://grandrapids.craigslist.org/",
                        "Holland": "https://holland.craigslist.org/",
                        "Jackson MI": "https://jxn.craigslist.org/",
                        "Kalamazoo": "https://kalamazoo.craigslist.org/",
                        "Lansing": "https://lansing.craigslist.org/",
                        "Monroe MI": "https://monroemi.craigslist.org/",
                        "Muskegon": "https://muskegon.craigslist.org/",
                        "North Michigan": "https://nmi.craigslist.org/",
                        "North MI": "https://nmi.craigslist.org/",
                        "Port Huron": "https://porthuron.craigslist.org/",
                        "Saginaw": "https://saginaw.craigslist.org/",
                        "Saginaw Island": "https://saginaw.craigslist.org/",
                        "Midland": "https://saginaw.craigslist.org/",
                        "Bay City": "https://saginaw.craigslist.org/",
                        "Southwest Michigan": "https://swmi.craigslist.org/",
                        "Southwest MI": "https://swmi.craigslist.org/",
                        "Thumb": "https://thumb.craigslist.org/",
                        "UP": "https://up.craigslist.org/",
                        "Upper Peninsula": "https://up.craigslist.org/",
                    },
                    "Minnesota": {
                        "Bemidji": "https://bemidji.craigslist.org/",
                        "Brainerd": "https://brainerd.craigslist.org/",
                        "Duluth": "https://duluth.craigslist.org/",
                        "Superior": "https://duluth.craigslist.org/",
                        "Mankato": "https://mankato.craigslist.org/",
                        "Minneapolis": "https://minneapolis.craigslist.org/",
                        "Minne": "https://minneapolis.craigslist.org/",
                        "St Paul": "https://minneapolis.craigslist.org/",
                        "Rochester": "https://rmn.craigslist.org/",
                        "Marshall": "https://marshall.craigslist.org/",
                        "Southwest Minnesota": "https://marshall.craigslist.org/",
                        "Southwest MN": "https://marshall.craigslist.org/",
                        "St Cloud": "https://stcloud.craigslist.org/",
                    },
                    "Mississippi": {
                        "Gulfport": "https://gulfport.craigslist.org/",
                        "Biloxi": "https://gulfport.craigslist.org/",
                        "Hattiesburg": "https://hattiesburg.craigslist.org/",
                        "Jackson": "https://jackson.craigslist.org/",
                        "Meridian": "https://meridian.craigslist.org/",
                        "North Miss": "https://northmiss.craigslist.org/",
                        "North Mississippi": "https://northmiss.craigslist.org/",
                        "North MS": "https://northmiss.craigslist.org/",
                        "Natchez": "https://natchez.craigslist.org/",
                        "Southwest Mississippi": "https://natchez.craigslist.org/",
                        "Southwest MS": "https://natchez.craigslist.org/",
                    },
                    "Missouri": {
                        "Columbia MO": "https://columbiamo.craigslist.org/",
                        "Jeff City": "https://columbiamo.craigslist.org/",
                        "Joplin": "https://joplin.craigslist.org/",
                        "Kansas City": "https://kansascity.craigslist.org/",
                        "Kirksville": "https://kirksville.craigslist.org/",
                        "Lake of the Ozarks": "https://loz.craigslist.org/",
                        "LOZ": "https://loz.craigslist.org/",
                        "Southeast Missouri": "https://semo.craigslist.org/",
                        "Southeast MO": "https://semo.craigslist.org/",
                        "Springfield MO": "https://springfield.craigslist.org/",
                        "St Joseph": "https://stjoseph.craigslist.org/",
                        "St Louis MO": "https://stlouis.craigslist.org/",
                    },
                    "Montana": {
                        "Billings": "https://billings.craigslist.org/",
                        "Bozeman": "https://bozeman.craigslist.org/",
                        "Butte": "https://butte.craigslist.org/",
                        "Great Falls": "https://greatfalls.craigslist.org/",
                        "Helena": "https://helena.craigslist.org/",
                        "Kalispell": "https://kalispell.craigslist.org/",
                        "Missoula": "https://missoula.craigslist.org/",
                        "East Montana": "https://montana.craigslist.org/",
                        "East MT": "https://montana.craigslist.org/",
                    },
                    "Nebraska": {
                        "Grand Island": "https://grandisland.craigslist.org/",
                        "Lincoln": "https://lincoln.craigslist.org/",
                        "North Platte": "https://northplatte.craigslist.org/",
                        "Omaha": "https://omaha.craigslist.org/",
                        "Council Bluffs": "https://omaha.craigslist.org/",
                        "Scottsbluff": "https://scottsbluff.craigslist.org/",
                    },
                    "Nevada": {
                        "Elko": "https://elko.craigslist.org/",
                        "Las Vegas": "https://lasvegas.craigslist.org/",
                        "Vegas": "https://lasvegas.craigslist.org/",
                        "Reno": "https://reno.craigslist.org/",
                        "Tahoe": "https://reno.craigslist.org/",
                    },
                    "New Hampshire": "https://nh.craigslist.org/",
                    "NH": "https://nh.craigslist.org/",
                    "New Jersey": {
                        "Central Jersey": "https://cnj.craigslist.org/",
                        "Central NJ": "https://cnj.craigslist.org/",
                        "Jersey Shore": "https://jerseyshore.craigslist.org/",
                        "Jersey": "https://jerseyshore.craigslist.org/",
                        "North Jersey": "https://newjersey.craigslist.org/",
                        "North NJ": "https://newjersey.craigslist.org/",
                        "South Jersey": "https://southjersey.craigslist.org/",
                        "South NJ": "https://southjersey.craigslist.org/",
                    },
                    "New Mexico": {
                        "Albuquerque": "https://albuquerque.craigslist.org/",
                        "Clovis": "https://clovis.craigslist.org/",
                        "Portales": "https://clovis.craigslist.org/",
                        "Farmington": "https://farmington.craigslist.org/",
                        "Las Cruces": "https://lascruces.craigslist.org/",
                        "Roswell": "https://roswell.craigslist.org/",
                        "Carlsbad": "https://roswell.craigslist.org/",
                        "Santa Fe": "https://santafe.craigslist.org/",
                        "Taos": "https://santafe.craigslist.org/",
                    },
                    "New York": {
                        "Albany": "https://albany.craigslist.org/",
                        "Binghamton": "https://binghamton.craigslist.org/",
                        "Buffalo": "https://buffalo.craigslist.org/",
                        "Catskills": "https://catskills.craigslist.org/",
                        "Chautauqua": "https://chautauqua.craigslist.org/",
                        "Elmira": "https://elmira.craigslist.org/",
                        "Corning": "https://elmira.craigslist.org/",
                        "Finger Lakes": "https://fingerlakes.craigslist.org/",
                        "Glens Falls": "https://glensfalls.craigslist.org/",
                        "Hudson Valley": "https://hudsonvalley.craigslist.org/",
                        "Ithaca": "https://ithaca.craigslist.org/",
                        "Long Island": "https://longisland.craigslist.org/",
                        "New York City": "https://newyork.craigslist.org/",
                        "NYC": "https://newyork.craigslist.org/",
                        "Oneonta": "https://oneonta.craigslist.org/",
                        "Plattsburgh": "https://plattsburgh.craigslist.org/",
                        "Adirondacks": "https://plattsburgh.craigslist.org/",
                        "Potsdam": "https://potsdam.craigslist.org/",
                        "Canton": "https://potsdam.craigslist.org/",
                        "Massena": "https://potsdam.craigslist.org/",
                        "Rochester": "https://rochester.craigslist.org/",
                        "Syracuse": "https://syracuse.craigslist.org/",
                        "Twin tiers": "https://twintiers.craigslist.org/",
                        "Utica": "https://utica.craigslist.org/",
                        "Rome NY": "https://utica.craigslist.org/",
                        "Oneida": "https://utica.craigslist.org/",
                        "Watertown": "https://watertown.craigslist.org/",
                    },
                    "North Carolina": {
                        "Asheville": "https://asheville.craigslist.org/",
                        "Boone": "https://boone.craigslist.org/",
                        "Charlotte": "https://charlotte.craigslist.org/",
                        "East NC": "https://eastnc.craigslist.org/",
                        "East North Carolina": "https://eastnc.craigslist.org/",
                        "Fayetteville": "https://fayetteville.craigslist.org/",
                        "Greensboro": "https://greensboro.craigslist.org/",
                        "Hickory": "https://hickory.craigslist.org/",
                        "Lenoir": "https://hickory.craigslist.org/",
                        "Jacksonville NC": "https://onslow.craigslist.org/",
                        "Onslow": "https://onslow.craigslist.org/",
                        "Onslow County": "https://onslow.craigslist.org/",
                        "Outer banks": "https://outerbanks.craigslist.org/",
                        "Raleigh": "https://raleigh.craigslist.org/",
                        "Durham": "https://raleigh.craigslist.org/",
                        "Chapel Hill": "https://raleigh.craigslist.org/",
                        "Wilmington": "https://wilmington.craigslist.org/",
                        "Winston": "https://winstonsalem.craigslist.org/",
                        "Winston Salem": "https://winstonsalem.craigslist.org/",
                        "Salem NC": "https://winstonsalem.craigslist.org/",
                    },
                    "North Dakota": {
                        "Bismarck": "https://bismarck.craigslist.org/",
                        "Fargo": "https://fargo.craigslist.org/",
                        "Moorhead": "https://fargo.craigslist.org/",
                        "Grand Forks": "https://grandforks.craigslist.org/",
                        "North ND": "https://nd.craigslist.org/",
                    },
                    "Ohio": {
                        "Akron": "https://akroncanton.craigslist.org/",
                        "Canton": "https://akroncanton.craigslist.org/",
                        "Ashtabula": "https://ashtabula.craigslist.org/",
                        "Athens OH": "https://athensohio.craigslist.org/",
                        "Chillicothe": "https://chillicothe.craigslist.org/",
                        "Cincinnati": "https://cincinnati.craigslist.org/",
                        "Cleveland": "https://cleveland.craigslist.org/",
                        "Columbus": "https://columbus.craigslist.org/",
                        "Dayton": "https://dayton.craigslist.org/",
                        "Springfield": "https://dayton.craigslist.org/",
                        "Lima": "https://limaohio.craigslist.org/",
                        "Findlay": "https://limaohio.craigslist.org/",
                        "Mansfield": "https://mansfield.craigslist.org/",
                        "Sandusky": "https://sandusky.craigslist.org/",
                        "Toledo": "https://toledo.craigslist.org/",
                        "Tuscarawas": "https://tuscarawas.craigslist.org/",
                        "Tuscarawas County": "https://tuscarawas.craigslist.org/",
                        "Youngstown": "https://youngstown.craigslist.org/",
                        "Zanesville": "https://zanesville.craigslist.org/",
                        "Cambridge": "https://zanesville.craigslist.org/",
                    },
                    "Oklahoma": {
                        "Lawton": "https://lawton.craigslist.org/",
                        "Enid": "https://enid.craigslist.org/",
                        "Northwest Ok": "https://enid.craigslist.org/",
                        "Northwest Oklahoma": "https://enid.craigslist.org/",
                        "Oklahoma City": "https://oklahomacity.craigslist.org/",
                        "OKC": "https://oklahomacity.craigslist.org/",
                        "Stillwater": "https://stillwater.craigslist.org/",
                        "Tulsa": "https://tulsa.craigslist.org/",
                    },
                    "Oregon": {
                        "Bend": "https://bend.craigslist.org/",
                        "Corvallis": "https://corvallis.craigslist.org/",
                        "Albany OR": "https://corvallis.craigslist.org/",
                        "East Oregon": "https://eastoregon.craigslist.org/",
                        "East OR": "https://eastoregon.craigslist.org/",
                        "Eugene": "https://eugene.craigslist.org/",
                        "Klamath Falls": "https://klamath.craigslist.org/",
                        "Medford": "https://medford.craigslist.org/",
                        "Ashland": "https://medford.craigslist.org/",
                        "Oregon Coast": "https://oregoncoast.craigslist.org/",
                        "Portland": "https://portland.craigslist.org/",
                        "Roseburg": "https://roseburg.craigslist.org/",
                        "Salem": "https://salem.craigslist.org/",
                    },
                    "Pennsylvania": {
                        "Altoona": "https://altoona.craigslist.org/",
                        "Johnstown": "https://altoona.craigslist.org/",
                        "Chambersburg": "https://chambersburg.craigslist.org/",
                        "Cumberland Valley": "https://chambersburg.craigslist.org/",
                        "Erie": "https://erie.craigslist.org/",
                        "Harrisburg": "https://harrisburg.craigslist.org/",
                        "Lancaster": "https://lancaster.craigslist.org/",
                        "Allentown": "https://allentown.craigslist.org/",
                        "Lehigh Valley": "https://allentown.craigslist.org/",
                        "Meadville": "https://meadville.craigslist.org/",
                        "Philadelphia": "https://philadelphia.craigslist.org/",
                        "Philly": "https://philadelphia.craigslist.org/",
                        "Pittsburgh": "https://pittsburgh.craigslist.org/",
                        "Poconos": "https://poconos.craigslist.org/",
                        "Reading": "https://reading.craigslist.org/",
                        "Scranton": "https://scranton.craigslist.org/",
                        "Wilkes Barre": "https://scranton.craigslist.org/",
                        "Penn State": "https://pennstate.craigslist.org/",
                        "Williamsport": "https://williamsport.craigslist.org/",
                        "York": "https://york.craigslist.org/",
                    },
                    "Rhode Island": {
                        "Providence": "https://providence.craigslist.org/",
                    },
                    "South Carolina": {
                        "Charleston": "https://charleston.craigslist.org/",
                        "Columbia": "https://columbia.craigslist.org/",
                        "Florence": "https://florencesc.craigslist.org/",
                        "Greenville": "https://greenville.craigslist.org/",
                        "Hilton Head": "https://hiltonhead.craigslist.org/",
                        "Myrtle Beach": "https://myrtlebeach.craigslist.org/",
                    },
                    "South Dakota": {
                        "Northeast SD": "https://nesd.craigslist.org/",
                        "Northeast South Dakota": "https://nesd.craigslist.org/",
                        "Pierre": "https://csd.craigslist.org/",
                        "Central SD": "https://csd.craigslist.org/",
                        "Central South Dakota": "https://csd.craigslist.org/",
                        "Rapid City": "https://rapidcity.craigslist.org/",
                        "West SD": "https://rapidcity.craigslist.org/",
                        "West South Dakota": "https://rapidcity.craigslist.org/",
                        "Sioux Falls": "https://siouxfalls.craigslist.org/",
                        "Southeast SD": "https://siouxfalls.craigslist.org/",
                        "Southeast South Dakota": "https://siouxfalls.craigslist.org/",
                        "South SD": "https://sd.craigslist.org/",
                        "South South Dakota": "https://sd.craigslist.org/",
                    },
                    "Tennessee": {
                        "Chattanooga": "https://chattanooga.craigslist.org/",
                        "Clarksville": "https://clarksville.craigslist.org/",
                        "Cookeville": "https://cookeville.craigslist.org/",
                        "Jackson TN": "https://jacksontn.craigslist.org/",
                        "Knoxville": "https://knoxville.craigslist.org/",
                        "Memphis": "https://memphis.craigslist.org/",
                        "Nashville": "https://nashville.craigslist.org/",
                        "Tri Cities": "https://tricities.craigslist.org/",
                    },
                    "Texas": {
                        "Abilene": "https://abilene.craigslist.org/",
                        "Amarillo": "https://amarillo.craigslist.org/",
                        "Austin": "https://austin.craigslist.org/",
                        "Beaumont": "https://beaumont.craigslist.org/",
                        "Brownsville": "https://brownsville.craigslist.org/",
                        "College Station": "https://collegestation.craigslist.org/",
                        "Corpus Christi": "https://corpuschristi.craigslist.org/",
                        "Dallas": "https://dallas.craigslist.org/",
                        "Fort Worth": "https://dallas.craigslist.org/",
                        "Nacogdoches": "https://nacogdoches.craigslist.org/",
                        "Deep East Texas": "https://nacogdoches.craigslist.org/",
                        "Deep East TX": "https://nacogdoches.craigslist.org/",
                        "Del Rio": "https://delrio.craigslist.org/",
                        "Eagle Pass": "https://delrio.craigslist.org/",
                        "El Paso": "https://elpaso.craigslist.org/",
                        "Galveston": "https://galveston.craigslist.org/",
                        "Houston": "https://houston.craigslist.org/",
                        "Killeen": "https://killeen.craigslist.org/",
                        "Temple": "https://killeen.craigslist.org/",
                        "Ft Hood": "https://killeen.craigslist.org/",
                        "Laredo": "https://laredo.craigslist.org/",
                        "Lubbock": "https://lubbock.craigslist.org/",
                        "McAllen": "https://mcallen.craigslist.org/",
                        "Edinburg": "https://mcallen.craigslist.org/",
                        "Odessa": "https://odessa.craigslist.org/",
                        "Midland": "https://odessa.craigslist.org/",
                        "San Angelo": "https://sanangelo.craigslist.org/",
                        "San Antonio": "https://sanantonio.craigslist.org/",
                        "San Marcos": "https://sanmarcos.craigslist.org/",
                        "Big Bend": "https://bigbend.craigslist.org/",
                        "Southwest Texas": "https://bigbend.craigslist.org/",
                        "Southwest TX": "https://bigbend.craigslist.org/",
                        "Texoma": "https://texoma.craigslist.org/",
                        "Tyler": "https://easttexas.craigslist.org/",
                        "East Texas": "https://easttexas.craigslist.org/",
                        "East TX": "https://easttexas.craigslist.org/",
                        "Victoria TX": "https://victoriatx.craigslist.org/",
                        "Waco": "https://waco.craigslist.org/",
                        "Wichita Falls": "https://wichitafalls.craigslist.org/",
                    },
                    "Utah": {
                        "Logan": "https://logan.craigslist.org/",
                        "Ogden": "https://ogden.craigslist.org/",
                        "Clearfield": "https://ogden.craigslist.org/",
                        "Provo": "https://provo.craigslist.org/",
                        "Orem": "https://provo.craigslist.org/",
                        "Salt Lake": "https://saltlakecity.craigslist.org/",
                        "Salt Lake City": "https://saltlakecity.craigslist.org/",
                        "St George": "https://stgeorge.craigslist.org/",
                    },
                    "Vermont": "https://vermont.craigslist.org/",
                    "Virginia": {
                        "Charlottesville": "https://charlottesville.craigslist.org/",
                        "Danville": "https://danville.craigslist.org/",
                        "Fredericksburg": "https://fredericksburg.craigslist.org/",
                        "Hampton Roads": "https://norfolk.craigslist.org/",
                        "Norfolk County": "https://norfolk.craigslist.org/",
                        "Harrisonburg": "https://harrisonburg.craigslist.org/",
                        "Lynchburg": "https://lynchburg.craigslist.org/",
                        "New River Valley": "https://blacksburg.craigslist.org/",
                        "Blacksburg": "https://blacksburg.craigslist.org/",
                        "Richmond VA": "https://richmond.craigslist.org/",
                        "Roanoke": "https://roanoke.craigslist.org/",
                        "Southwest VA": "https://swva.craigslist.org/",
                        "Southwest Virginia": "https://swva.craigslist.org/",
                        "Winchester": "https://winchester.craigslist.org/",
                    },
                    "Washington": {
                        "Bellingham": "https://bellingham.craigslist.org/",
                        "Kennewick": "https://kpr.craigslist.org/",
                        "Pasco": "https://kpr.craigslist.org/",
                        "Richland": "https://kpr.craigslist.org/",
                        "Moses Lake": "https://moseslake.craigslist.org/",
                        "Olympic": "https://olympic.craigslist.org/",
                        "Pullman": "https://pullman.craigslist.org/",
                        "Moscow WA": "https://pullman.craigslist.org/",
                        "Seattle": "https://seattle.craigslist.org/",
                        "Tacoma": "https://seattle.craigslist.org/",
                        "Skagit County": "https://skagit.craigslist.org/",
                        "Skagit": "https://skagit.craigslist.org/",
                        "San Juan Islands": "https://skagit.craigslist.org/",
                        "SJI": "https://skagit.craigslist.org/",
                        "Spokane": "https://spokane.craigslist.org/",
                        "Coeur dalene": "https://spokane.craigslist.org/",
                        "Wenatchee": "https://wenatchee.craigslist.org/",
                        "Yakima": "https://yakima.craigslist.org/",
                    },
                    "West Virginia": {
                        "Charleston WV": "https://charlestonwv.craigslist.org/",
                        "Martinsburg": "https://martinsburg.craigslist.org/",
                        "East WV": "https://martinsburg.craigslist.org/",
                        "East West Virginia": "https://martinsburg.craigslist.org/",
                        "Huntington": "https://huntington.craigslist.org/",
                        "Ashland": "https://huntington.craigslist.org/",
                        "Morgantown": "https://morgantown.craigslist.org/",
                        "Wheeling WV": "https://wheeling.craigslist.org/",
                        "North WV": "https://wheeling.craigslist.org/",
                        "North West Virginia": "https://wheeling.craigslist.org/",
                        "Parkersburg": "https://parkersburg.craigslist.org/",
                        "Marietta": "https://parkersburg.craigslist.org/",
                        "South WV": "https://swv.craigslist.org/",
                        "South West Virginia": "https://swv.craigslist.org/",
                        "West WV": "https://wv.craigslist.org/",
                        "West West Virginia": "https://wv.craigslist.org/",
                    },
                    "Wisconsin": {
                        "Appleton": "https://appleton.craigslist.org/",
                        "Oshkosh": "https://appleton.craigslist.org/",
                        "Fond du Lac": "https://appleton.craigslist.org/",
                        "FDL": "https://appleton.craigslist.org/",
                        "Eau Claire": "https://eauclaire.craigslist.org/",
                        "Green Bay": "https://greenbay.craigslist.org/",
                        "Janesville": "https://janesville.craigslist.org/",
                        "Kenosha": "https://racine.craigslist.org/",
                        "Racine": "https://racine.craigslist.org/",
                        "La Crosse": "https://lacrosse.craigslist.org/",
                        "Madison WI": "https://madison.craigslist.org/",
                        "Milwaukee": "https://milwaukee.craigslist.org/",
                        "North WI": "https://northernwi.craigslist.org/",
                        "North Wisconsin": "https://northernwi.craigslist.org/",
                        "Sheboygan": "https://sheboygan.craigslist.org/",
                        "Wausau": "https://wausau.craigslist.org/",
                    },
                    "Wyoming": "https://wyoming.craigslist.org/",
                },
                "Alaska": {
                    "Anchorage": "https://anchorage.craigslist.org/",
                    "Fairbanks": "https://fairbanks.craigslist.org/",
                    "Kenai Peninsula": "https://kenai.craigslist.org/",
                    "Southeast Alaska": "https://juneau.craigslist.org/",
                    "Southeast AK": "https://juneau.craigslist.org/",
                },
                "Hawaii": "https://honolulu.craigslist.org/",
                "US Territories": {
                    "Guam": "https://micronesia.craigslist.org/",
                    "Micronesia": "https://micronesia.craigslist.org/",
                    "Puerto Rico": "https://puertorico.craigslist.org/",
                    "Virgin Islands": "https://virgin.craigslist.org/",
                    "Virgin": "https://virgin.craigslist.org/",
                },
            },
        },
        "Oceania": {
            "Australia": {
                "Adelaide": "https://adelaide.craigslist.org/",
                "Brisbane": "https://brisbane.craigslist.org/",
                "Cairns": "https://cairns.craigslist.org/",
                "Canberra": "https://canberra.craigslist.org/",
                "Darwin": "https://darwin.craigslist.org/",
                "Gold Coast": "https://goldcoast.craigslist.org/",
                "Melbourne": "https://melbourne.craigslist.org/",
                "New Castle": "https://ntl.craigslist.org/",
                "Perth": "https://perth.craigslist.org/",
                "Sydney": "https://sydney.craigslist.org/",
                "Hobart": "https://hobart.craigslist.org/",
                "Tasmania": "https://hobart.craigslist.org/",
                "Wollongong": "https://wollongong.craigslist.org/",
            },
            "New Zealand": {
                "Auckland": "https://auckland.craigslist.org/",
                "Christchurch": "https://christchurch.craigslist.org/",
                "Dunedin": "https://dunedin.craigslist.org/",
                "Wellington": "https://wellington.craigslist.org/",
            },
        },
    },
}
