user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0'

[selectors]
    [selectors.links]
    resumes = '//a[@href="/search/rrr"]'
    event_calendar = '//a[@href="/search/eee"]'

        [selectors.links.community]
        all = '//a[@href="/search/ccc"]'
        activities = '//a[@href="/search/act"]'
        artists = '//a[@href="/search/ats"]'
        childcare = '//a[@href="/search/kid"]'
        classes = '//a[@href="/search/cls"]'
        events = '//a[@href="/search/eve"]'
        general = '//a[@href="/search/com"]'
        groups = '//a[@href="/search/grp"]'
        local_news = '//a[@href="/search/vnn"]'
        lost_found = '//a[@href="/search/laf"]'
        missed_connections = '//a[@href="/search/mis"]'
        musicians = '//a[@href="/search/muc"]'
        pets = '//a[@href="/search/pet"]'
        politics = '//a[@href="/search/pol"]'
        rants_raves = '//a[@href="/search/rnr"]'
        rideshare = '//a[@href="/search/rid"]'
        volunteers = '//a[@href="/search/vol"]'

        [selectors.links.services]
        all = '//a[@href="/search/bbb"]'
        automotive = '//a[@href="/search/aos"]'
        beauty = '//a[@href="/search/bts"]'
        cell_mobile = '//a[@href="/search/cms"]'
        computer = '//a[@href="/search/cps"]'
        creative = '//a[@href="/search/crs"]'
        cycle = '//a[@href="/search/cys"]'
        event = '//a[@href="/search/evs"]'
        farm_garden = '//a[@href="/search/fgs"]'
        financial = '//a[@href="/search/fns"]'
        health_well = '//a[@href="/search/hws"]'
        household = '//a[@href="/search/hss"]'
        labor_move = '//a[@href="/search/lbs"]'
        legal = '//a[@href="/search/lgs"]'
        lessons = '//a[@href="/search/lss"]'
        marine = '//a[@href="/search/mas"]'
        pet = '//a[@href="/search/pas"]'
        real_estate = '//a[@href="/search/rts"]'
        skilled_trade = '//a[@href="/search/sks"]'
        sm_biz_ads = '//a[@href="/search/biz"]'
        travel_vac = '//a[@href="/search/trv"]'
        write_ed_tran = '//a[@href="/search/wet"]'

        [selectors.links.housing]
        all = '//a[@href="/search/hhh"]'
        apts_housing = '//a[@href="/search/apa"]'
        housing_swap = '//a[@href="/search/swp"]'
        housing_wanted = '//a[@href="/search/hsw"]'
        office_commercial = '//a[@href="/search/off"]'
        parking_storage = '//a[@href="/search/prk"]'
        for_sale = '//a[@href="/search/rea"]'
        rooms_shared = '//a[@href="/search/roo"]'
        rooms_wanted = '//a[@href="/search/sha"]'
        sublets_temporary = '//a[@href="/search/sub"]'
        vacation_rentals = '//a[@href="/search/vac"]'

        [selectors.links.for_sale]
        all = '//a[@href="/search/sss"]'
        antiques = '//a[@href="/search/ata"]'
        appliances = '//a[@href="/search/ppa"]'
        arts_crafts = '//a[@href="/search/ara"]'
        atv_utv_sno = '//a[@href="/search/sna"]'
        auto_parts = '//a[@href="/search/pta"]'
        aviation = '//a[@href="/search/ava"]'
        baby_kid = '//a[@href="/search/baa"]'
        barter = '//a[@href="/search/bar"]'
        beauty_health = '//a[@href="/search/haa"]'
        bike_parts = '//a[@href="/search/bip"]'
        bikes = '//a[@href="/search/bia"]'
        boat_parts = '//a[@href="/search/bpa"]'
        boats = '//a[@href="/search/boo"]'
        books = '//a[@href="/search/bka"]'
        business = '//a[@href="/search/bfa"]'
        cars_trucks = '//a[@href="/search/cta"]'
        cds_dvd_vhs = '//a[@href="/search/ema"]'
        cell_phones = '//a[@href="/search/moa"]'
        clothes_acc = '//a[@href="/search/cla"]'
        collectibles = '//a[@href="/search/cba"]'
        computer_parts = '//a[@href="/search/syp"]'
        computers = '//a[@href="/search/sya"]'
        electronics = '//a[@href="/search/ela"]'
        farm_garden = '//a[@href="/search/gra"]'
        free = '//a[@href="/search/zip"]'
        furniture = '//a[@href="/search/fua"]'
        garage_sale = '//a[@href="/search/gms"]'
        general = '//a[@href="/search/foa"]'
        heavy_equip = '//a[@href="/search/hva"]'
        household = '//a[@href="/search/hsa"]'
        jewelry = '//a[@href="/search/jwa"]'
        materials = '//a[@href="/search/maa"]'
        motorcycle_parts = '//a[@href="/search/mpa"]'
        motorcycles = '//a[@href="/search/mca"]'
        music_instr = '//a[@href="/search/msa"]'
        photo_video = '//a[@href="/search/pha"]'
        rvs_camp = '//a[@href="/search/rva"]'
        sporting = '//a[@href="/search/sga"]'
        tickets = '//a[@href="/search/tia"]'
        tools = '//a[@href="/search/tla"]'
        toys_games = '//a[@href="/search/taa"]'
        trailers = '//a[@href="/search/tra"]'
        video_gaming = '//a[@href="/search/vga"]'
        wanted = '//a[@href="/search/waa"]'
        wheels_tires = '//a[@href="/search/wta"]'

        [selectors.links.jobs]
        all = '//a[@href="/search/jjj"]'
        accounting = '//a[@href="/search/acc"]'
        admin_office = '//a[@href="/search/ofc"]'
        arch_engineering = '//a[@href="/search/egr"]'
        art_media_design = '//a[@href="/search/med"]'
        biotech_science = '//a[@href="/search/sci"]'
        business_mgmt = '//a[@href="/search/bus"]'
        customer_service = '//a[@href="/search/csr"]'
        education = '//a[@href="/search/edu"]'
        etc_misc = '//a[@href="/search/etc"]'
        food_bev_hosp = '//a[@href="/search/fbh"]'
        general_labor = '//a[@href="/search/lab"]'
        government = '//a[@href="/search/gov"]'
        hr = '//a[@href="/search/hum"]'
        legal = '//a[@href="/search/lgl"]'
        manufacturing = '//a[@href="/search/mnu"]'
        marketing = '//a[@href="/search/mar"]'
        medical_health = '//a[@href="/search/hea"]'
        nonprofit = '//a[@href="/search/npo"]'
        real_estate = '//a[@href="/search/rej"]'
        retail = '//a[@href="/search/ret"]'
        sales = '//a[@href="/search/sls"]'
        salon_fitness = '//a[@href="/search/spa"]'
        security = '//a[@href="/search/sec"]'
        skilled_trade = '//a[@href="/search/trd"]'
        software = '//a[@href="/search/sof"]'
        systems_network = '//a[@href="/search/sad"]'
        technical_support = '//a[@href="/search/tch"]'
        transport = '//a[@href="/search/trp"]'
        tv_film_video = '//a[@href="/search/tfr"]'
        web_info_design = '//a[@href="/search/web"]'
        writing_editing = '//a[@href="/search/wri"]'

        [selectors.links.gigs]
        all = '//a[@href="/search/ggg"]'
        computer = '//a[@href="/search/cpg"]'
        creative = '//a[@href="/search/crg"]'
        crew = '//a[@href="/search/cwg"]'
        domestic = '//a[@href="/search/dmg"]'
        event = '//a[@href="/search/evg"]'
        labor = '//a[@href="/search/lbg"]'
        talent = '//a[@href="/search/tlg"]'
        writing = '//a[@href="/search/wrg"]'

    [selectors.for_sale]
    search = '//input[@placeholder="search for sale"]'
    results = "//div[contains(@class, 'results')]/ol"
    next = "//div[contains(@class, 'bottom')]//button[contains(@class, 'cl-next-page')]"

    [selectors.result_options]
    box_button = "//button[contains(@class, 'cl-search-view-mode')]"
    list = "//div[contains(@class, 'bd-list-box')]//button[contains(@class, 'cl-search-view-mode-list')]"
    thumb = "//div[contains(@class, 'bd-list-box')]//button[contains(@class, 'cl-search-view-mode-thumb')]"
    preview = "//div[contains(@class, 'bd-list-box')]//button[contains(@class, 'cl-search-view-mode-card')]"
    grid = "//div[contains(@class, 'bd-list-box')]//button[contains(@class, 'cl-search-view-mode-grid')]"
    gallery = "//div[contains(@class, 'bd-list-box')]//button[contains(@class, 'cl-search-view-mode-gallery')]"
    map = "//div[contains(@class, 'bd-list-box')]//button[contains(@class, 'cl-search-view-mode-map')]"
